name: cross build pacman
# auto-task.start-build-time = ?
on: { "push": { "paths": [".github/workflows/build-pacman.yml"] } }
# on: { "schedule": [{ "cron": "22 3 10 2,6,10 *" }] }

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - rv64gc
          - armv7a
          - ppc64le
          - ppc
          - ppc64
          # - loong64
          # - i486
          - i686
          # - x86
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: zsh --pipefail -fex {0}
    env:
      ZSH_REPO: ghcr.io/2moe/zsh-static:x64
    steps:
      - name: install zsh
        shell: sh -e {0}
        run: docker run --rm -v /usr/local/bin:/app ${{env.ZSH_REPO}} cp /opt/bin/zsh /app/
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: install qemu-user using apt
        if: contains(fromJson('["ppc64le", "ppc", "ppc64", "loong64"]'), matrix.arch)
        run: sudo apt update && sudo apt-get install -y qemu-user-static

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 1
      - name: build & push
        env:
          ARCHIMG_TMM_ARCH: ${{matrix.arch}}
        run: ./src/build-pacman/build
