name: clean old images
# auto-task.start-build-time = ?
on: { "push": { "paths": [".github/workflows/clean.yml"] } }
# on: { "schedule": [{ "cron": "10 2 * * 5" }] }

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: debian*, *
          cut-off: 2 days ago UTC
          keep-at-least: 1
          account-type: org
          org-name: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          untagged-only: true
          token-type: github-token
