name: clean old images
# auto-task.start-build-time = ?
# on: { "push": { "paths": [".github/workflows/clean.yml"] } }
on: { "schedule": [{ "cron": "26 10 * * 6" }] }

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          # arch*,pacman*,debian*,ubuntu
          image-names: '*'
          cut-off: 1 day ago UTC
          keep-at-least: 1
          account-type: org
          org-name: 2cd
          token: ${{ secrets.RM_GHCR_PAT }}
          untagged-only: true

      - name: Delete 2moe images
        uses: snok/container-retention-policy@v2
        with:
          image-names: '*'
          cut-off: 1 day ago UTC
          keep-at-least: 1
          account-type: personal
          token: ${{ secrets.RM_GHCR_PAT }}
          untagged-only: true
